### ISSUE TITLE
What portion of the units is still usable?

### ISSUE THREAD

**Issue by mrmeszaros** [zoqaeski/systemd-user-units#2]
Is there any change with the user session data problem?
Any updates on how much of these units are still usable?

I checked the `ssh-agent.service` and it is mostly usable. It only needs some kind of hook to update the shell environment with `SSH_AGENT_PID` on service start.

**Comment by zoqaeski** [comment]
I have absolutely no idea, as I haven't used this setup since 2014—I switched to GNOME with a few useful extensions around that time, and after a few months getting used to the quirks I'm pretty happy with it now. I've got no interest in maintaining this, as even back then it was a bit of a nuisance to get working, and some of the user session capabilities were never intended by the systemd devs, which is why it was rendered obsolete by the update to systemd-206. 

I'm keeping it online for posterity in case someone else finds it useful, nothing more. By all means, fork this project and see if you can get it working, but the documentation is largely obsolete and the setup is officially unsupported so you're effectively on your own. Sorry, I can't really be of more help.
